/* ezels.js — ezelsbruggetjes per begrip (getoond op de kaartjes en bij foutfeedback). */
window.EZELS = {
  "wetenschap": "Kennis opdoen én gebruiken. Niet alleen weten, ook toepassen.",
  "natuurwetenschap": "Natuur + wetenschap. Biologie, natuurkunde en scheikunde horen er alle drie bij.",
  "biologie": "Bio = leven. Biologie gaat over alles wat leeft.",
  "natuurkunde": "Natuurkunde = tijdelijk. Smelten, uitzetten, verdampen: de stof blijft dezelfde.",
  "scheikunde": "Scheikunde = blijvend. Verbranden, roesten, oxideren: er ontstaat een nieuwe stof.",
  "röntgenfoto's": "Botten houden de straling tegen en worden wit. Spieren laten hem door en worden donker.",
  "wetenschappelijke methode": "Vraag → hypothese → experiment bedenken → uitvoeren → tabel → conclusie. Zes stappen, vaste volgorde.",
  "onderzoeksvraag": "Herken hem aan het vraagteken, of aan 'X wil weten hoe...'.",
  "hypothese": "Hypothese = voorspelling vooraf. 'Ik denk dat...'. Hij mág fout zijn.",
  "zintuig": "Zien, horen, ruiken, voelen, proeven. Horen/zien/voelen mag altijd, ruiken voorzichtig, proeven nooit.",
  "meetinstrument": "Gereedschap om te meten: liniaal, weegschaal, maatcilinder, thermometer, stopwatch.",
  "meetwaarde": "Het kale getal. In '52 kg' is dat de 52.",
  "eenheid": "Past achter een getal. '25 meter' kan, '25 lengte' niet.",
  "grootheid": "Wat je meet. Lengte, massa, volume, tijd, temperatuur, dichtheid.",
  "indicator": "Verandert van kleur als de stof er is. Geeft ja of nee, geen getal.",
  "jodium": "Bruingeel wordt donkerblauw bij zetmeel.",

  "massa": "Hoeveel stof er in zit. Meten met de weegschaal, in gram of kilogram. 1 kg = 1000 g.",
  "volume": "Hoeveel ruimte het inneemt. Maatcilinder of l × b × h. 1 L = 1000 mL en 1 mL = 1 cm³.",
  "onderdompelmethode": "eindstand − beginstand. Eindstand is altijd de grootste, dus die staat vooraan.",
  "dichtheid": "De massa van één blokje van 1 cm³. Formule: massa / volume, eenheid g/cm³.",
  "stofeigenschap": "Verandert niet met de hoeveelheid. Zaag het blok doormidden: de dichtheid blijft gelijk.",
  "beginstand": "Altijd éérst aflezen, vóór het voorwerp erin gaat. Anders neemt het water mee.",
  "eindstand": "De stand als het voorwerp helemaal onder water is.",
  "drijven": "Dichtheid kleiner dan 1,0 g/cm³. Denk aan hout (0,58) en ijs (0,92).",
  "zinken": "Dichtheid groter dan 1,0 g/cm³. Denk aan glas (2,6) en goud (19,3).",
  "zweven": "Dichtheid precies 1,0 g/cm³: niet omhoog, niet omlaag.",
  "pond": "Was in elke stad anders (Amsterdam 494 g, Den Haag 470 g). Daarom kwam in 1820 de kilogram.",
  "metrieke stelsel": "1820, Nederland. Vaste eenheden die overal hetzelfde zijn.",

  "weegschaal": "Massa, in gram of kilogram.",
  "maatcilinder": "Volume van een vloeistof. Aflezen op ooghoogte, bij het vlakke deel.",
  "thermometer": "Temperatuur, in graden Celsius.",
  "liniaal": "Lengte, in centimeter of meter.",
  "stopwatch": "Tijd, in seconden.",
  "kg": "1 kg = 1000 g.",
  "g/cm3": "Gram per kubieke centimeter: hoeveel gram in élk blokje van 1 cm³.",
  "1,0": "De dichtheid van water. Jouw vaste ijkpunt bij drijven en zinken.",
  "lengte x breedte x hoogte": "Drie richtingen, dus drie lengtes keer elkaar. cm × cm × cm = cm³.",
  "massa / volume": "Delen. Hoeveel gram zit er in één blokje van 1 cm³?",
  "eindstand - beginstand": "Het water dat omhoog kwam, is precies de ruimte van het voorwerp."
};
